include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    omit_local_variable_types: ignore
    always_specify_types: warning
    avoid_types_on_closure_parameters: ignore
    always_use_package_imports: error
    constant_identifier_names: ignore

linter:
  rules:
    - always_specify_types
    - always_use_package_imports
    - constant_identifier_names